### ISSUE TITLE
Problem with deploying as of Meteor 2.3

### ISSUE THREAD

**Issue by JackAdams** [andruschka/pm2-meteor#91]
Since updating to Meteor 2.3 (and to node 14.7.3 on the server), after running:
```
pm2-meteor deploy
```
I'm having to do this on the server before the app will run without errors:
```
cd /opt/meteor-apps/myAppName/bundle/programs/server
node npm-rebuild
```
As soon as I've done that on the server, the app is up and running again.

Does anyone have any ideas about why this might be the case or how I can fix it so that `pm2-meteor deploy` can just be issued from the client without any commands needing to be run on the server?

(I love `pm2-meteor` by the way. Thanks for making it available to all of us @andruschka !)

**Comment by eleventy** [comment]
Are you running the same version of Node on the dev-client as on the server? Some node modules are binaries that are build when you `npm install`. If the version of Node is different, you might have an incompatible binary, which is fixed by the rebuild command.

I use nvm on my dev machine to easily switch node versions.

**Comment by JackAdams** [comment]
Hi @eleventy, yes I'm fairly sure I'm running the same versions of node on dev machine and server (using `n` on the server to update to new versions - similar to what you're doing with `nvm`).  I appreciate you taking the time to make this suggestion though; I'm going to go and double check node versions now.

**Comment by JackAdams** [comment]
Never got to the bottom of this, but outlined a workaround here for anyone who runs into the same problem: #96
